### ISSUE TITLE
Shuttle v0.37.0 breaking change

### ISSUE THREAD

**Issue by j0lol** [joshua-mo-143/shuttle-seaorm#1]
in shuttle-service 0.37.0, the generic is removed from ResourceBuilder, and the methods new and build are removed.

https://docs.rs/shuttle-service/0.37.0/shuttle_service/trait.ResourceBuilder.html

**Comment by joshua-mo-143** [comment]
Hey, thanks for opening an issue!

Since Shuttle added retrieving multiple types out of an annotation, I will probably add this feature to the official crate and deprecate this plugin.
